### ISSUE TITLE
Bugs: The mobile view does not work properly 

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/Blockchain-Book-vol2#1]
## 4. you can add side navbar for linked  ```<li><a href="#....">1. ....</a></li> ``` tag 

**Problem 👇**
![Screenshot 2022-10-05 121619](https://user-images.githubusercontent.com/97989643/193997749-b2b7e22f-1fc9-4c8d-82a1-bdb81819a6c7.png)

### Process  
1. **Fork this repo** 
2. **Clone this repo**
3. Give a **branch name** - ```git branch your_branch_name```
4. Check your **branch** - ```git checkout your_branch_name```
5. For checking **status** - ``` git status```
6. **Adding the changes** - ```git add .```
7. **Commit** - ```git commit -m"your changes"```
8. **Push the changed files** - ```git push origin your_branch_name```
9. Then open your repo check changes and click on **compare & pull request** and write what questions and answers you added then commit 

10. I will merge the branch after checking all the questions, answers, and explanation

**Comment by mani1911** [comment]
hey pls assign this to me under hacktoberfest

**Comment by Joshua-Nweze** [comment]
Hi @Subham-Maity, I want to work on this, please assign it to me. Thank you

**Comment by Subham-Maity** [comment]
@Joshua-Nweze Ok do this

**Comment by Joshua-Nweze** [comment]
Can you please label the repo as hacktoberfest.

**Comment by Subham-Maity** [comment]
@Joshua-Nweze sure

**Comment by Joshua-Nweze** [comment]
Thank you

**Comment by Joshua-Nweze** [comment]
Should I use Bootstrap or CSS media queries? Can I use anyone?

**Comment by Subham-Maity** [comment]
@Joshua-Nweze You can use whatever you want

**Comment by Joshua-Nweze** [comment]
Ok, thanks.

**Comment by Subham-Maity** [comment]
@Joshua-Nweze Thanks a lot for your help!
